FROM python:3.12

WORKDIR /app

COPY ./requirements.txt .

COPY ./src .

ENV PYTHONPATH=/app/src

RUN mkdir -p ./output

RUN pip install -r requirements.txt

ENTRYPOINT ["python", "accumulated_precipitation.py"]
